routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


/* CMS BackOffice Routes */

Route::group(['prefix' => 'cms', 'namespace' => 'cms'], function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::group(['name' => 'blog.'], function () {
        Route::resource('blogs', 'BlogController');
        Route::post("ckeditor/image/upload", "BlogController@uploadCKImage")->name("ckeditor.upload.image");
    });

    Route::resource('seo', 'SeoController');
    Route::resource('banner', 'BannerController');

    Route::resource("gallery", "AlbumController");

    Route::prefix("gallery/{gallery}/images")->name("gallery.images")->group(function () {
        Route::post("store", "AlbumController@uploadImage")->name(".store");
        Route::put("{media}", "AlbumController@updateImage")->name(".update");
        Route::delete("{media}", "AlbumController@destroyImage")->name(".destroy");
    });
});

/* ---------- CMS BackOffice Routes End ---------- */

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\ModelTraits;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Album extends Model
{
    use SoftDeletes, ModelTraits;

    CONST DESTINATION_PATH = 'images/album/';

    /**
     * [RELATIONSHIPS]
     */
    function galleries()
    {
        return $this->morphMany('App\Models\Media', 'parent');
    }
}

app/Http/Controllers/CMS/AlbumController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Models\Album;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Validator;
use App\Models\Media;

class AlbumController extends Controller
{
    protected $folder = "CMS.albums";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::get();

        return view($this->folder . ".index", compact('albums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->folder . ".create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->toArray(), [
            "title" => "required|string|max:191",
            "description" => "nullable|string"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withInput()->withErrors($validate);
        }

        $album = new Album();
        $album->name = $request->get("title");
        $album->description = $request->get("description");
        $album->publish = $request->has("status");
        $album->save();

        return redirect()->route("gallery.index")->withSuccess('Ablum has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $gallery)
    {
        $album = Album::with([
            "galleries" => function ($query) {
                $query->orderBy("sequence", "asc");
            }
        ])->where("id", $gallery->id)
            ->first();

        return view($this->folder . ".show", compact('album'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $gallery)
    {
        $album = $gallery;
        return view($this->folder . ".edit", compact('album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $gallery)
    {
        $album = $gallery;
        $validate = Validator::make($request->toArray(), [
            "title" => "required|string|max:191",
            "description" => "nullable|string"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withInput()->withErrors($validate);
        }

        $album->name = $request->get("title");
        $album->description = $request->get("description");
        $album->publish = $request->has("status");
        $album->save();

        return redirect()->route("gallery.index")->withSuccess('Ablum has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $gallery)
    {
        if (!empty($gallery)) {
            $gallery->galleries()->delete();
            $gallery->delete();
        }

        session()->flash("success", "Album has been deleted.");
        return response()->json([
            "deleted" => 1,
            "message" => 'Album has been deleted.'
        ]);
    }

    public function uploadImage(Request $request, Album $gallery)
    {
        $validator = Validator::make($request->all(), [
            'file.*' => 'required|file|max:10240|mimes:jpeg,jpg,png',
        ]);

        $validator->setAttributeNames([
            'file.*' => 'File',
        ]);

        if ($validator->fails()) {
            return response($validator->messages()->all());
        }

        foreach ($request->file("file") as $file) {
            $file_name = str_random(20);
            $ext = $file->getClientOriginalExtension();
            $file_original_name = $file->getClientOriginalName();
            $file_size = $file->getSize();
            $file_mime_type = $file->getMimeType();
            $destination_path = Album::DESTINATION_PATH;
            $file->move($destination_path, $file_name . '.' . $ext);
            $file_url = $destination_path . $file_name . '.' . $ext;

            $media = new Media();
            $media->parent_type = Album::class;
            $media->parent_id = $gallery->id;
            $media->path = $file_url;
            $media->original_name = $file_original_name;
            $media->extension = $ext;
            $media->mime = $file_mime_type;
            $media->size_in_kb = $file_size;
            $media->save();
        }

        return response(200);
    }

    public function updateImage(Request $request, Album $gallery, Media $media)
    {
        $media->sequence = $request->get("seq", $media->sequence);
        $media->publish = $request->has("status");
        $media->save();

        return redirect()->back()->withSuccess('Gallery Image has been updated.');
    }

    public function destroyImage(Request $request, Album $gallery, Media $media)
    {
        if (!empty($media)) {
            $media->delete();
        }

        return redirect()->back()->withSuccess('Gallery Image has been deleted.');
    }
}

app/Http/Controllers/CMS/BannerController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Banner;
use Validator, File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $results = Banner::where('active', 1)->get();

        return view('CMS.banner', ['results' => $results]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
			'file.*' => 'required|file|max:10240|mimes:jpeg,jpg,png',
        ]);
        
		$validator->setAttributeNames([
			'file.*' => 'File',
		]);
    
		if($validator->fails()) {
			return response($validator->messages()->all());
		}
		
		foreach($request->file("file") as $file)
		{
            $file_name = str_random(20);
            $ext = $file->getClientOriginalExtension();
            $destination_path = 'images/banner/';
            $file->move($destination_path,$file_name.'.'.$ext);
            $file_url = $destination_path.$file_name.'.'.$ext;

            $last_seq = (Banner::get()->count() != 0) ? Banner::orderBy('seq','desc')->first()->seq : 0;
			
            $banner = new Banner();
            $banner->img_url = $file_url;
            $banner->seq = $last_seq + 1;
			$banner->save();
        }
		
        return response(200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
			'link' => 'url',
        ]);
        
		$validator->setAttributeNames([
			'file' => 'Link',
		]);
    
		if($validator->fails()) {
            return redirect()->back()->withErrors($validator, "formerror");
        }
        
        $banner = Banner::find($id);

        $current_seq = $banner->seq;
        $target_seq = $request->input('seq');

        if($current_seq < $target_seq) {
            $banner_higher_seq = Banner::where('seq', '>', $current_seq)->where('seq', '<=', $target_seq)->get();
            foreach($banner_higher_seq as $banner_higher){
                $banner_higher->seq -= 1;
                $banner_higher->save();
            }
        } elseif ($current_seq > $target_seq) {
            $banner_lower_seq = Banner::where('seq', '<', $current_seq)->where('seq', '>=', $target_seq)->get();
            foreach($banner_lower_seq as $banner_lower){
                $banner_lower->seq += 1;
                $banner_lower->save();
            }
        }

        $banner->seq = $target_seq;
        $banner->title = $request->input('title');
        $banner->desc = $request->input('desc');
        $banner->link = $request->input('link');
        $banner->save();

        return redirect()->back()->withSuccess('Banner has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $current_seq = Banner::find($id)->seq;
        Banner::where('id', $id)->delete();

        $banner_higher_seq = Banner::where('seq', '>', $current_seq)->get();
        foreach($banner_higher_seq as $banner_higher){
            $banner_higher->seq -= 1;
            $banner_higher->save();
        }

        return redirect()->back()->withSuccess('Banner has been deleted.');
    }
}

app/Http/Controllers/CMS/BlogController.php
<?php

namespace App\Http\Controllers\CMS;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Models\Blog;


class BlogController extends Controller
{
    protected $upload_path = '/app/public/blog_media';
    protected $asset_path = '/storage/blog_media/';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::get();

        return view('CMS.blog.index',compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('CMS.blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "title" => "required|string",
            "content" => "required|string"
        ]);
        $title = $request->get('title');
        $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title)));
        $slugs = Blog::where('slug',$newSlug)->get();
        if(!empty($slugs)){
            $count = 1;
            foreach($slugs as $slug){
                if($slug->slug != $newSlug.'-'.$count){
                    $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title))).'-'.$count;
                }
                $count++;
            }
        }
        $blog = (new Blog)->storeRecord([
            "title" => $title,
            "slug" => $newSlug,
            "content" => $request->get('content'),
            "status" => 1,
            "written_by" => 0
        ],true);

        session()->flash('success','New Blog Created.');
        return redirect()->route('blogs.show',['blog'=> $blog->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        return view('CMS.blog.show',compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        return view('CMS.blog.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        $this->validate($request, [
            "title" => "required|string",
            "content" => "required|string"
        ]);
        $title = $request->get('title');
        $data = [
            "content" => $request->get('content')
        ];
        if($blog->title != $title){
            $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title)));
            $slugs = Blog::where('slug',$newSlug)->get();
            if(!empty($slugs)){
                $count = 1;
                foreach($slugs as $slug){
                    if($slug->slug != $newSlug.'-'.$count){
                        $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title))).'-'.$count;
                    }
                    $count++;
                }
            }
            $data['slug'] = $newSlug;
            $data['title'] = $title;
        }
        $result = $blog->updateRecord($data,true);

        session()->flash('success','Blog Updated.');
        return redirect()->route('blogs.show',['blog'=> $result->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function uploadCKImage(Request $request) {

        $this->upload_path = storage_path().$this->upload_path;

        $validator = Validator::make($request->toArray(), [
                    "upload" => "required|file|image|max:2048"
                        ], [
                    "upload.required" => "Please select an image to upload.",
                    "upload.file" => "Please upload an image.",
                    "upload.image" => "Invalid file type. Please upload image type only. (jpg, jpeg, png, bmp and svg)",
                    "upload.max" => "Upload limit exceeded, please upload the image within 2MB."
        ]);


        if ($validator->fails()) {
            return response()->json([
                        "uploaded" => 0,
                        "error" => [
                            "message" => $validator->errors()->first()
                        ]
            ]);
        }

        if ($request->hasFile("upload")) {

            $file = $request->file("upload");
            $extension = strtolower($file->getClientOriginalExtension());
            $file_name = "media_".date("Ymdhis").rand(11,99).'.'.$extension;
            $upload = $file->move($this->upload_path,$file_name);

            if($upload){
                $url = asset($this->asset_path.$file_name);
                return response()->json([
                            "uploaded" => 1,
                            "fileName" => $file_name,
                            "url" => $url
                ]);
            }else {
                return response()->json([
                            "uploaded" => 0,
                            "error" => [
                                "message" => "Fail to upload image."
                            ]
                ]);
            }
        }
    }
}

app/Http/Controllers/CMS/HomeController.php
<?php

namespace App\Http\Controllers\CMS;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index () {
        return view('CMS.dashboard');
    }
}

resources/views/CMS/albums/create.blade.php
@extends('CMS.layouts.app')
@section('head')

@endsection

@section('content')

<!-- Main content -->
<section class="content">
  @include('CMS.components.messages')
  <!-- Default box -->
<div class="card">
    <form id="submit-form" action="{{ route('gallery.store') }}" method="post">
        <div class="card-header">
            <h3 class="card-title">Create Album</h3>
        </div>
        <div class="card-body">
            @csrf
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" placeholder="Title" value="{{ old('title') }}" />
            </div>

            <div class="form-group">
                <label for="content">Description</label>
                <textarea class="form-control" name="description">{!! old('description') !!}</textarea>
            </div>

            <div class="form-group">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="status" id="status" />
                    <label class="form-check-label" for="status">Publish</label>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        
        <div class="card-footer">
            <a href="{{ route('gallery.index') }}" class="btn btn-warning">Back</a>
            <button class="btn btn-success btn-submit">Confirm</button>
        </div>
        <!-- /.card-footer-->
    </form>
</div>
<!-- /.card -->

</section>
<!-- /.content -->

@stop

@section('script')
@endsection

resources/views/CMS/albums/edit.blade.php
@extends('CMS.layouts.app')
@section('head')

@endsection

@section('content')

<!-- Main content -->
<section class="content">
  @include('CMS.components.messages')
  <!-- Default box -->
<div class="card">
    <form id="submit-form" action="{{ route('gallery.update', ['gallery' => $album->id]) }}" method="post">
        <div class="card-header">
            <h3 class="card-title">Edit Album</h3>
        </div>
        <div class="card-body">
            @csrf
            @method("PUT")
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" name="title" placeholder="Title" value="{{ old('title', $album->name) }}" />
            </div>

            <div class="form-group">
                <label for="content">Description</label>
                <textarea class="form-control" name="description">{!! old('description', $album->description) !!}</textarea>
            </div>

            <div class="form-group">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" name="status" id="status" {{ old('status', $album->publish) == 1 ? 'checked' : '' }} />
                    <label class="form-check-label" for="status">Publish</label>
                </div>
            </div>
        </div>
        <!-- /.card-body -->
        
        <div class="card-footer">
            <a href="{{ route('gallery.index') }}" class="btn btn-warning">Back</a>
            <button class="btn btn-success btn-submit">Confirm</button>
        </div>
        <!-- /.card-footer-->
    </form>
</div>
<!-- /.card -->

</section>
<!-- /.content -->

@stop

@section('script')
@endsection

resources/views/CMS/albums/index.blade.php
@extends('CMS.layouts.app')
@section('head')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('CMS/plugins/adminlte/datatables/dataTables.bootstrap4.css') }}">
@endsection

@section('content')

<!-- Main content -->
<section class="content">
    @include('CMS.components.messages')
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Create Album
                <a href="{{ route('gallery.create') }}" class="btn-sm btn-success">Create</a>
            </h3>
        </div>
        <div class="card-body">
            <table id="index-table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Publish</th>
                        <th>Images</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($albums as $album)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $album->name }}</td>
                            <td>{{ strip_tags(Str::limit($album->description,20)) }}</td>
                            <td>
                                {{ $album->publish_text }}
                            </td>
                            <td>
                                {{ $album->galleries->count() }}
                            </td>
                            <td>
                                <a class="btn btn-primary" href="{{ route('gallery.show',['gallery'=>$album->id]) }}"><i class="fa fa-search" aria-hidden="true"></i></a>
                                <a class="btn btn-warning" href="{{ route('gallery.edit',['gallery'=>$album->id]) }}"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                <button class="btn btn-danger delete_link" href="{{ route('gallery.show',['gallery'=>$album->id]) }}" data-name="{{ $album->title }}"><i class="fa fa-trash" aria-hidden="true"></i></button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>No.</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Publish</th>
                        <th>Images</th>
                        <th>Actions</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.card-body -->

    </div>
    <!-- /.card -->

</section>
<!-- /.content -->




@stop
@section('script')
<!-- DataTables -->
<script src="{{ asset('CMS/plugins/adminlte/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('CMS/plugins/adminlte/datatables/dataTables.bootstrap4.js') }}"></script>
<script>
    $('#index-table').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
    });
</script>
@endsection