routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


/* CMS BackOffice Routes */

Route::group(['prefix' => 'cms', 'namespace' => 'cms'], function () {
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    Route::group(['name' => 'blog.'], function () {
        Route::resource('blogs', 'BlogController');
        Route::post("ckeditor/image/upload", "BlogController@uploadCKImage")->name("ckeditor.upload.image");
    });

    Route::resource('seo', 'SeoController');
    Route::resource('banner', 'BannerController');

    Route::resource("gallery", "AlbumController");

    Route::prefix("gallery/{gallery}/images")->name("gallery.images")->group(function () {
        Route::post("store", "AlbumController@uploadImage")->name(".store");
        Route::put("{media}", "AlbumController@updateImage")->name(".update");
        Route::delete("{media}", "AlbumController@destroyImage")->name(".destroy");
    });
});

/* ---------- CMS BackOffice Routes End ---------- */

app/Http/Controllers/CMS/AlbumController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Models\Album;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Validator;
use App\Models\Media;

class AlbumController extends Controller
{
    protected $folder = "CMS.albums";

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $albums = Album::get();

        return view($this->folder . ".index", compact('albums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view($this->folder . ".create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->toArray(), [
            "title" => "required|string|max:191",
            "description" => "nullable|string"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withInput()->withErrors($validate);
        }

        $album = new Album();
        $album->name = $request->get("title");
        $album->description = $request->get("description");
        $album->publish = $request->has("status");
        $album->save();

        return redirect()->route("gallery.index")->withSuccess('Ablum has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $gallery)
    {
        $album = Album::with([
            "galleries" => function ($query) {
                $query->orderBy("sequence", "asc");
            }
        ])->where("id", $gallery->id)
            ->first();

        return view($this->folder . ".show", compact('album'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $gallery)
    {
        $album = $gallery;
        return view($this->folder . ".edit", compact('album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $gallery)
    {
        $album = $gallery;
        $validate = Validator::make($request->toArray(), [
            "title" => "required|string|max:191",
            "description" => "nullable|string"
        ]);

        if ($validate->fails()) {
            return redirect()->back()->withInput()->withErrors($validate);
        }

        $album->name = $request->get("title");
        $album->description = $request->get("description");
        $album->publish = $request->has("status");
        $album->save();

        return redirect()->route("gallery.index")->withSuccess('Ablum has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $gallery)
    {
        if (!empty($gallery)) {
            $gallery->galleries()->delete();
            $gallery->delete();
        }

        session()->flash("success", "Album has been deleted.");
        return response()->json([
            "deleted" => 1,
            "message" => 'Album has been deleted.'
        ]);
    }

    public function uploadImage(Request $request, Album $gallery)
    {
        $validator = Validator::make($request->all(), [
            'file.*' => 'required|file|max:10240|mimes:jpeg,jpg,png',
        ]);

        $validator->setAttributeNames([
            'file.*' => 'File',
        ]);

        if ($validator->fails()) {
            return response($validator->messages()->all());
        }

        foreach ($request->file("file") as $file) {
            $file_name = str_random(20);
            $ext = $file->getClientOriginalExtension();
            $file_original_name = $file->getClientOriginalName();
            $file_size = $file->getSize();
            $file_mime_type = $file->getMimeType();
            $destination_path = Album::DESTINATION_PATH;
            $file->move($destination_path, $file_name . '.' . $ext);
            $file_url = $destination_path . $file_name . '.' . $ext;

            $media = new Media();
            $media->parent_type = Album::class;
            $media->parent_id = $gallery->id;
            $media->path = $file_url;
            $media->original_name = $file_original_name;
            $media->extension = $ext;
            $media->mime = $file_mime_type;
            $media->size_in_kb = $file_size;
            $media->save();
        }

        return response(200);
    }

    public function updateImage(Request $request, Album $gallery, Media $media)
    {
        $media->sequence = $request->get("seq", $media->sequence);
        $media->publish = $request->has("status");
        $media->save();

        return redirect()->back()->withSuccess('Gallery Image has been updated.');
    }

    public function destroyImage(Request $request, Album $gallery, Media $media)
    {
        if (!empty($media)) {
            $media->delete();
        }

        return redirect()->back()->withSuccess('Gallery Image has been deleted.');
    }
}

app/Http/Controllers/CMS/BannerController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Banner;
use Validator, File;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $results = Banner::where('active', 1)->get();

        return view('CMS.banner', ['results' => $results]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
			'file.*' => 'required|file|max:10240|mimes:jpeg,jpg,png',
        ]);
        
		$validator->setAttributeNames([
			'file.*' => 'File',
		]);
    
		if($validator->fails()) {
			return response($validator->messages()->all());
		}
		
		foreach($request->file("file") as $file)
		{
            $file_name = str_random(20);
            $ext = $file->getClientOriginalExtension();
            $destination_path = 'images/banner/';
            $file->move($destination_path,$file_name.'.'.$ext);
            $file_url = $destination_path.$file_name.'.'.$ext;

            $last_seq = (Banner::get()->count() != 0) ? Banner::orderBy('seq','desc')->first()->seq : 0;
			
            $banner = new Banner();
            $banner->img_url = $file_url;
            $banner->seq = $last_seq + 1;
			$banner->save();
        }
		
        return response(200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
			'link' => 'url',
        ]);
        
		$validator->setAttributeNames([
			'file' => 'Link',
		]);
    
		if($validator->fails()) {
            return redirect()->back()->withErrors($validator, "formerror");
        }
        
        $banner = Banner::find($id);

        $current_seq = $banner->seq;
        $target_seq = $request->input('seq');

        if($current_seq < $target_seq) {
            $banner_higher_seq = Banner::where('seq', '>', $current_seq)->where('seq', '<=', $target_seq)->get();
            foreach($banner_higher_seq as $banner_higher){
                $banner_higher->seq -= 1;
                $banner_higher->save();
            }
        } elseif ($current_seq > $target_seq) {
            $banner_lower_seq = Banner::where('seq', '<', $current_seq)->where('seq', '>=', $target_seq)->get();
            foreach($banner_lower_seq as $banner_lower){
                $banner_lower->seq += 1;
                $banner_lower->save();
            }
        }

        $banner->seq = $target_seq;
        $banner->title = $request->input('title');
        $banner->desc = $request->input('desc');
        $banner->link = $request->input('link');
        $banner->save();

        return redirect()->back()->withSuccess('Banner has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $current_seq = Banner::find($id)->seq;
        Banner::where('id', $id)->delete();

        $banner_higher_seq = Banner::where('seq', '>', $current_seq)->get();
        foreach($banner_higher_seq as $banner_higher){
            $banner_higher->seq -= 1;
            $banner_higher->save();
        }

        return redirect()->back()->withSuccess('Banner has been deleted.');
    }
}

app/Http/Controllers/CMS/BlogController.php
<?php

namespace App\Http\Controllers\CMS;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use App\Models\Blog;


class BlogController extends Controller
{
    protected $upload_path = '/app/public/blog_media';
    protected $asset_path = '/storage/blog_media/';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::get();

        return view('CMS.blog.index',compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('CMS.blog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "title" => "required|string",
            "content" => "required|string"
        ]);
        $title = $request->get('title');
        $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title)));
        $slugs = Blog::where('slug',$newSlug)->get();
        if(!empty($slugs)){
            $count = 1;
            foreach($slugs as $slug){
                if($slug->slug != $newSlug.'-'.$count){
                    $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title))).'-'.$count;
                }
                $count++;
            }
        }
        $blog = (new Blog)->storeRecord([
            "title" => $title,
            "slug" => $newSlug,
            "content" => $request->get('content'),
            "status" => 1,
            "written_by" => 0
        ],true);

        session()->flash('success','New Blog Created.');
        return redirect()->route('blogs.show',['blog'=> $blog->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        return view('CMS.blog.show',compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        return view('CMS.blog.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        $this->validate($request, [
            "title" => "required|string",
            "content" => "required|string"
        ]);
        $title = $request->get('title');
        $data = [
            "content" => $request->get('content')
        ];
        if($blog->title != $title){
            $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title)));
            $slugs = Blog::where('slug',$newSlug)->get();
            if(!empty($slugs)){
                $count = 1;
                foreach($slugs as $slug){
                    if($slug->slug != $newSlug.'-'.$count){
                        $newSlug = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(" ", "-", strtolower($title))).'-'.$count;
                    }
                    $count++;
                }
            }
            $data['slug'] = $newSlug;
            $data['title'] = $title;
        }
        $result = $blog->updateRecord($data,true);

        session()->flash('success','Blog Updated.');
        return redirect()->route('blogs.show',['blog'=> $result->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function uploadCKImage(Request $request) {

        $this->upload_path = storage_path().$this->upload_path;

        $validator = Validator::make($request->toArray(), [
                    "upload" => "required|file|image|max:2048"
                        ], [
                    "upload.required" => "Please select an image to upload.",
                    "upload.file" => "Please upload an image.",
                    "upload.image" => "Invalid file type. Please upload image type only. (jpg, jpeg, png, bmp and svg)",
                    "upload.max" => "Upload limit exceeded, please upload the image within 2MB."
        ]);


        if ($validator->fails()) {
            return response()->json([
                        "uploaded" => 0,
                        "error" => [
                            "message" => $validator->errors()->first()
                        ]
            ]);
        }

        if ($request->hasFile("upload")) {

            $file = $request->file("upload");
            $extension = strtolower($file->getClientOriginalExtension());
            $file_name = "media_".date("Ymdhis").rand(11,99).'.'.$extension;
            $upload = $file->move($this->upload_path,$file_name);

            if($upload){
                $url = asset($this->asset_path.$file_name);
                return response()->json([
                            "uploaded" => 1,
                            "fileName" => $file_name,
                            "url" => $url
                ]);
            }else {
                return response()->json([
                            "uploaded" => 0,
                            "error" => [
                                "message" => "Fail to upload image."
                            ]
                ]);
            }
        }
    }
}

app/Http/Controllers/CMS/HomeController.php
<?php

namespace App\Http\Controllers\CMS;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index () {
        return view('CMS.dashboard');
    }
}

resources/views/CMS/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2019 <a href="https://www.etctech.com.my/">ETC Tech</a>.</strong>
    All rights reserved.
</footer>

resources/views/CMS/layouts/sidenav.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('dashboard') }}" class="brand-link">
        <img src="{{ asset('CMS/images/etc.png') }}" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">ETC CMS</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('CMS/images/user.png') }}" class="img-circle elevation-2">
            </div>
            <div class="info">
                <a href="javascript:void(0)" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">

                <li class="nav-item">
                    <a href="{{ route('dashboard') }}" class="nav-link {{ Route::currentRouteName() == 'dashboard' ? 'active' : '' }}">
                        <i class="nav-icon fa fa-dashboard"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{{route('banner.index')}}" class="nav-link">
                        <i class="nav-icon fa fa-bookmark"></i>
                        <p>
                            Banner
                        </p>
                    </a>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-home"></i>
                        <p>
                            Home
                        </p>
                    </a>
                </li>

                <li class="nav-item has-treeview">
                    <a href="javascript:void(0)" class="nav-link">
                        <i class="nav-icon fa fa-tree"></i>
                        <p>
                            Category
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Overview</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Create New</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Edit</p>
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-item has-treeview {{ Request::segment(2) == 'seo' ? 'menu-open' : '' }}">
                    <a href="javascript:void(0)" class="nav-link">
                        <i class="nav-icon fa fa-search"></i>
                        <p>
                            SEO
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('seo.index') }}" class="nav-link {{ Route::currentRouteName() == 'seo.index' ? 'active' : '' }}">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>All</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('seo.create') }}" class="nav-link {{ Route::currentRouteName() == 'seo.create' ? 'active' : '' }}">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Create</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview {{ Request::segment(2) == 'blogs' ? 'menu-open' : '' }}">
                    <a href="javascript:void(0)" class="nav-link">
                        <i class="nav-icon fa fa-coffee"></i>
                        <p>
                            Blogs
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('blogs.index') }}" class="nav-link {{ Route::currentRouteName() == 'blogs.index' ? 'active' : '' }}">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>All</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('blogs.create') }}" class="nav-link {{ Route::currentRouteName() == 'blogs.create' ? 'active' : '' }}">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Create</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview {{ Request::segment(2) == 'gallery' ? 'menu-open' : '' }}">
                    <a href="javascript:void(0)" class="nav-link">
                        <i class="nav-icon fa fa-image"></i>
                        <p>
                            Gallery
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('gallery.index') }}" class="nav-link {{ Route::currentRouteName() == 'gallery.index' ? 'active' : '' }}">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>All</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('gallery.create') }}" class="nav-link {{ Route::currentRouteName() == 'gallery.create' ? 'active' : '' }}">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Create</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview">
                    <a href="javascript:void(0)" class="nav-link">
                        <i class="nav-icon fa fa-calendar"></i>
                        <p>
                            Events
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Overview</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Create New</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Edit</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item has-treeview">
                    <a href="javascript:void(0)" class="nav-link">
                        <i class="nav-icon fa fa-tags"></i>
                        <p>
                            Promotions
                            <i class="right fa fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Overview</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Create New</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="javascript:void(0)" class="nav-link">
                                <i class="fa fa-circle-o nav-icon"></i>
                                <p>Edit</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/CMS/layouts/topnav.blade.php
<nav class="main-header navbar navbar-expand bg-white navbar-light border-bottom">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fa fa-bars"></i></a>
        </li>
    </ul>

    <ul class="navbar-nav ml-auto">
    <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa fa-bell-o"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">

                <span class="dropdown-item dropdown-header">15 Notifications</span>

                <div class="dropdown-divider"></div>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>

                <div class="dropdown-divider"></div>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>

                <div class="dropdown-divider"></div>

                <a href="#" class="dropdown-item">
                    <i class="fa fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>

                <div class="dropdown-divider"></div>

                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="#">
                <i class="fa fa-sign-out"></i>
            </a>
        </li>
    </ul>
</nav>
<!-- /.navbar -->